### ISSUE TITLE
Passing "Controlling the widget" as props.

### ISSUE THREAD

**Issue by sohansarma** [chardmd/react-drift#12]
Can we have the widget controller as a props. As I am unable to control the widget in my react application. I will be very happy if someone help me out with the same. :))

**Comment by smithmr** [comment]
+1 here!

**Comment by chardmd** [comment]
this feature is now available

https://github.com/chardmd/react-drift/commit/fe2d9198322d6f4e5466b4ab44c90e629b71dbf3

thanks to @mitchell-bu
