### ISSUE TITLE
Call setUserAttributes()?

### ISSUE THREAD

**Issue by wootwoot1234** [chardmd/react-drift#13]
I noticed that the following methods are available:

https://github.com/chardmd/react-drift/blob/dae52dfbd73ccbb459e4357c77a3ddcc776d37f2/src/Drift.jsx#L25

Is it possible to add `setUserAttributes()`?  If it's as easy as adding it to the list I'm happy to send in a PR.

**Comment by wootwoot1234** [comment]
I just ran a test and it worked so I created a PR.

https://github.com/chardmd/react-drift/pull/14

**Comment by chardmd** [comment]
cool. i just merged your PR.
