### ISSUE TITLE
Updating attributes after mount lifecycle

### ISSUE THREAD

**Issue by atinder** [chardmd/react-drift#8]
the component is not watching new props.
I want to change attributes once the user is logged in.

**Comment by Plouufff** [comment]
@atinder you should call again addIdentityVariables method inside a componentDidUpdate

**Comment by atinder** [comment]
@Plouufff ideally it should be handled like this https://github.com/chardmd/react-drift/pull/10/files#diff-5ac4fa77cbfa65ca7e25b70823611d49R69
if we call addIdentityVariables multiple time it will append script tag multiple times.

**Comment by chardmd** [comment]
this has been fixed.
